### ISSUE TITLE
QS animation not working in landscape mode. 

### ISSUE THREAD

**Issue by shivap1998** [wasdennnoch/AndroidN-ify#1010]
Hi there. 
I am on Oneplus X using the Oct-M rom (6.0.1) and am using the latest snapshot version of Android n-ify.
The animation works perfectly in portrait mode but when i use it in landscape mode, the icons stay at the top and duplicate icons come down. After this, the small icons stay at the top forever (even in portrait mode) untill i restart the system ui. 

Here is the log file from xposed. 
https://drive.google.com/file/d/0B2Sc8mcpnRCMN2FBYlBSelFwZjA/view?usp=drivesdk

Thanks a lot for your awesome work and i hope to hear from you regarding this bug. Please tell me if i need to provide anything else.

**Comment by wasdennnoch** [comment]
Does that still happen with the latest build?

**Comment by shivap1998** [comment]
Nope! It's fixed! But ever since I changed (upgraded) the Android n-ify from the one that we get in xPosed to the one that is linked here, I get comparatively less battery life. Is there anything that you've added that should use more battery or have I done something wrong?

(PS: I don't have Google assistant enabled)

**Comment by wasdennnoch** [comment]
I don't know; it's quite possible that the battery may drain faster because hooks ren't free, they come with the cost of performance and we are hooking some methods that get called every frame. But there's no workaround for that. It could also be that Xposed itself drains battery and not just the odule, but you said you only experienced it with a snapshot build. Last possibility is that something crashes silently which also impacts performance, you can post your Xposed log so I can take a look if you want. If there is nothing interesting in the log it's most probably just because Xposed requires more resources and we can't change that.
