### ISSUE TITLE
"x" in network icons

### ISSUE THREAD

**Issue by LosTigeros** [wasdennnoch/AndroidN-ify#1166]
How I can get rid of "x" in mobile network icons?
The phone is MTK based phone.
http://vpx.pl/i/2016/11/07/Screenshot_2016-11-07-08-19-49.png

Im using latest build of Android N-ify

There is nothing in logcat, xposed log.

**Comment by wasdennnoch** [comment]
Disable the no mobile data indicator in the module settings.

**Comment by LosTigeros** [comment]
Thats not working. I have active network connection.

**Comment by wasdennnoch** [comment]
So you disabled the setting in the module options and still get that indicator?

**Comment by LosTigeros** [comment]
Yes

**Comment by LosTigeros** [comment]
This is a video about that bug: https://youtu.be/eL42zqwsOmg

**Comment by FreakyEnderman** [comment]
If you are using another module it may cause that to happen. I was using Flat Style Bar Indicators with this option on I either had a X or a LTE logo and it never faded away. Then I disabled it. But your issue is more weird than mine. Try deleting the cache or data of the module. Explore your other module that might do the same. Maybe it is not N-ify related issue.

**Comment by LosTigeros** [comment]
I dont use other modules which interact with status bar

**Comment by FreakyEnderman** [comment]
@LosTigeros Then it is obviously n-ify bug

**Comment by LosTigeros** [comment]
Error.log: https://drive.google.com/file/d/0B5IKSY3sCuE9WGZabnlrZnhfT1E/view?usp=drivesdk
