### ISSUE TITLE
Daily translations pulls

### ISSUE THREAD

**Issue by licaon-kter** [wasdennnoch/AndroidN-ify#1201]
Now there's a one week lag, although many translations are up to date.

**Comment by wasdennnoch** [comment]
One week. Wow. There was a time where the translations didn't get an update for almost a month and nobody complained.

**Comment by licaon-kter** [comment]
It's more about the rhythm, since the CI gets builds out on every commit, we end up with half translated features. While an app that's not at all translated is ok, one that has parts translated feels incomplete and the untranslated part stings out. :)

I know it's not "omg an issue", but since translations are available, just use them.

**Comment by wasdennnoch** [comment]
That means I have to go to Crowdin every day, build the project there, download the results, mive them to N-ify, fix all the stuff Crowdin fucks up (non-escaped semicolons and stuff) and then push it. That's the current procedure and it's not a quick procedure at all. There is also a git integration for Crowdin, but it wasn't available when I initially created the project and that's why there is none yet. I've recently seen it being available though, I'll have a look.

**Comment by licaon-kter** [comment]
Oh, sorry then, I had no idea it's so convoluted, I though it's just a simple push/pull of strings*.xml. :(
