### ISSUE TITLE
System UI crash on Stock

### ISSUE THREAD

**Issue by eagle3000** [wasdennnoch/AndroidN-ify#651]
Hi, 
The System UI is crashing from time to time. Can't really make out a pattern because it appears to be kind of random when and how often.

Using Bullhead on MTC19Z. Xposed 86 and Android N-ify Build 491 from here: https://ci.paphonb.xyz/jenkins/job/AndroidN-ify/
Faced this issue for at least the two weeks I'm using N-ify so it doesn't seem to be an issue that's been introduced recently (but rather one that simply isn't fixed)

Xposed log: http://pastebin.com/28PYUj3z
Android log: https://puu.sh/qkZOT/65c4515c0a.png

Thanks :)

**Comment by eagle3000** [comment]
So I realized we're already on Build 497.
Updated and got it to crash.

Xposed log: http://pastebin.com/2cCbzpLH
Android log: https://puu.sh/ql39A/5652e57753.png

**Comment by wasdennnoch** [comment]
This crash seems to be caused by the SystemUI itself and not directly by the module, it happens when a notification gets posted. I think I had a similar type of crash some time ago, but it was the ROM's fault. Please test if the issue persists without the module. It could also be there because of the modified layout and the SystemUI can't find a view because of that. I'd need your SystemUI to fix that, but deodexed, otherwise I can't help you.

**Comment by wasdennnoch** [comment]
No response -
